# Generated by Django 3.1.6 on 2021-02-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
